/**
 * HTTP Status Codes and Error Codes
 */

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  GONE: 410,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SERVER_ERROR: 'SERVER_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  USER_EXISTS: 'USER_EXISTS',
  PHONE_EXISTS: 'PHONE_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DEPRECATED: 'DEPRECATED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ASTROLOGER_NOT_FOUND: 'ASTROLOGER_NOT_FOUND',
  CONSULTATION_NOT_FOUND: 'CONSULTATION_NOT_FOUND',
  HOROSCOPE_NOT_FOUND: 'HOROSCOPE_NOT_FOUND',
  HOROSCOPE_EXISTS: 'HOROSCOPE_EXISTS',
  BIRTH_DETAILS_REQUIRED: 'BIRTH_DETAILS_REQUIRED',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;
